# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os, sys
from datetime import date

# -- Project Path -----------------------------------------------------
sys.path.insert(0, os.path.abspath('../../src'))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "Aircraft Data Hierarchy"
copyright = f"{date.today().year}, The Boeing Company"
author = "Ranald Engelbeck, Eduardo Ocampo"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "sphinx.ext.doctest",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx_automodapi.automodapi",
    "sphinx.ext.napoleon",
    "sphinx.ext.mathjax",
    "autodocsumm",
	"myst_nb",
]

# https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#
myst_enable_extensions = [
    "amsmath",
    "dollarmath",
    "replacements",
    "smartquotes",
    "strikethrough",
    "tasklist",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Autodoc configuration ---------------------------------------------------

# Place documentation generated by automodule and autoclass in the order they
# are in the source file.
autodoc_member_order = "bysource"

# Make it so that classes will not look like functions
autodoc_class_signature = "separated"

# Parameter types will only be in the description. Thus making things cleaner
autodoc_typehints = "description"


autodoc_default_options = {
    "autosummary": True,
    "autosummary-sections": "Attributes ;; Methods",
    "members": True,
    "special-members": True,
    "show-inheritance": True,
    "exclude-members": "__weakref__, model_config, __pydantic_fields_set__, __pydantic_extra__, __pydantic_private__, __class_vars__, __private_attributes__, __pydantic_complete__, __pydantic_computed_fields__, __pydantic_core_schema__, __pydantic_custom_init__, __pydantic_decorators__, __pydantic_fields__, __pydantic_generic_metadata__, __pydantic_parent_namespace__, __pydantic_post_init__, __pydantic_serializer__, __pydantic_validator__, __signature__"
}

# hide module names
toc_object_entries = False
add_module_names = False

# -- Options for HTML output -------------------------------------------------
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]

# Options for RTD theme
# https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html
html_theme_options = {
    'prev_next_buttons_location': 'None',
    'navigation_depth': 7, # Controls SideBar Expand/Close Levels
    'collapse_navigation': False,
    'sticky_navigation': True,
}

html_css_files = [
    'custom.css',
]
