name: Build and Deploy Documentation

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install .[docs]

      - name: Build documentation
        id: build
        run: |
          cd docs
          sphinx-build -M html ./source ./_build

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: docs/_build/html

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
